### PR TITLE
logging the error for artifact reader

### PR DESCRIPTION
**Pull request by dheerajgupta217**
Fixes issue #??

## Proposed Changes
  -
  -
  
## Testing Done
  -
  -

### CODE REVIEW

**Comment by dheerajgupta217** [comment]
logging the error for artifact reader

**Comment by davemasselink** [comment]
regarding the failing checks: those are due to the coverage numbers dropping slightly with a new SLOC but no corresponding increase in testing coverage

this is also something we can let slide for a simple PR

**Comment by dheerajgupta217** [comment]
> [CLA assistant check](https://cla-assistant.io/keikoproj/active-monitor?pullRequest=25)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keikoproj/active-monitor?pullRequest=25) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keikoproj/active-monitor?pullRequest=25) it.

I have signed your CLA. Kindly merge it ahead.

**Comment by dheerajgupta217** [comment]
> > [CLA assistant check](https://cla-assistant.io/keikoproj/active-monitor?pullRequest=25)
> > Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keikoproj/active-monitor?pullRequest=25) before we can accept your contribution.
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keikoproj/active-monitor?pullRequest=25) it.
> 
> I have signed your CLA. Kindly merge it ahead.

image
Here, in the image you can check this.

**Comment by davemasselink** [comment]
hey @dheerajgupta217, the issue is that your commits came in associated with a different user, "dgupta3c". Either you'll need to sign-in with that user account and sign the CLA in that context

OR

you can try to setup an account alias along the lines of what's discussed in a similar scenario in this PR: https://github.com/keikoproj/instance-manager/pull/55#issuecomment-538779039

**Comment by dgupta3c** [comment]
@davemasselink I have accepted CLA with dgupta3c user and I think we are good to go with it

**Pull request merged**
